### ISSUE TITLE
Extension should not emit raw HTML

### ISSUE THREAD

**Issue by mojavelinux** [eshepelyuk/asciidoctor-plantuml.js#10]
An Asciidoctor syntax extension should not emit raw HTML. Instead, it should return an AST node, which will get converted to HTML automatically by the converter. This does mean giving up some control over the HTML that is created, but it also means that the extension can be used to produce other formats, such as DocBook.

(If you want to customize the HTML, then that should be handled using a separate, supplemental extension to the HTML converter).

**Comment by mojavelinux** [comment]
The resulting HTML is going to look like this:

```html
<div id="myId" class="imageblock plantuml">
<div class="content">
<img src="http://localhost:8080/png/SoWkIImgAStDuKhCoKnELT2rKqZAJ-9oICrB0Ga20000" alt="diagram">
</div>
</div>
```

How important is the data-pumlid? Can that just be an id attribute?

**Comment by mojavelinux** [comment]
I don't think the message for a misconfigured server should end up in the generated document. Instead, it should just echo back the listing block to the AST and emit a warning to the console. Eventually, this warning will go to the Asciidoctor logger, once one exists....or you can add your own logger in the extension.

**Comment by mojavelinux** [comment]
In general, we should try to match what Asciidoctor Diagram does for plantuml as much as possible so documents that have plantuml blocks are portable.

**Comment by mojavelinux** [comment]
The first positional attribute should not be the ID. The ID already has a place in the block name.

```
[plantuml#idname]
```

The first positional attribute can be an explicit name for the generated file, like Asciidoctor Diagram does.

```
[plantuml,diagram-name]
```

(In Asciidoctor Diagram, the second positional attribute is the diagram format, such as svg or png).

**Comment by eshepelyuk** [comment]
You may remove `data-pumlid`
