### ISSUE TITLE
Add support for ditaa and dot diagrams

### ISSUE THREAD

**Issue by mojavelinux** [eshepelyuk/asciidoctor-plantuml.js#16]
In addition to its native format, PlantUML can also process ditaa and dot (graphviz) diagrams. Add support for these blocks.

This is actually a two-part issue. In addition to supporting ditaa and dot, the `@start` and `@end` directives should be optional, inferred by the block style (like in Asciidoctor Diagram).

In other words, it should be possible to define a ditaa diagram using a ditaa block:

```
[ditaa]
----
/----------\   +-------------+
|cAAA      |   |             |
|          +---+ Application |
| Database |   |      cRED{d}|
|       {s}|   +-------------+
\-----+----/
----
```

And a UML diagram using a plantuml block:

```
[plantuml]
----
alice -> bob
bob ..> alice
----
```

The appropriate directives should be added if missing (e.g., `@startditaa/@endditaa` or `@startuml/@enduml`).

The block style is available using the call Opal.hash_get(attrs, 1).

**Comment by mojavelinux** [comment]
Here's how the block would be registered:

```js
registry.block('plantuml', plantumlBlock)
registry.block('ditaa', plantumlBlock)
registry.block('grapviz', plantumlBlock)
```

Here's how the directives can be detected and added if necessary:

```js
let diagramText = reader.getString()
if (!/^@start([a-z]+)\n[\s\S]*\n@end\1$/.test(diagramText)) {
  const diagramType = Opal.hash_get(attrs, 1)
  if (diagramType === 'plantuml') {
    diagramText = '@startuml\n' + diagramText + '\n@enduml'
  } else if (diagramType === 'ditaa') {
    diagramText = '@startditaa\n' + diagramText + '\n@endditaa'
  } else if (diagramType === 'graphviz') {
    diagramText = '@startdot\n' + diagramText + '\n@enddot'
  }
}
```

(You could make the regexp even more specific)

**Comment by eshepelyuk** [comment]
@mojavelinux one note, the extension name becomes ambigous on introducing those changes :(

**Comment by mojavelinux** [comment]
Actually I don't think so. PlantUML has assimilated these other tools and
seems committed to this consolidation, so I think this still all falls
under the umbrella of PlantUML as the engine.

**Comment by Mogztter** [comment]
@mojavelinux @eshepelyuk is the PlantUML server already able to render  ditaa and graphviz (dot) diagrams ?

**Comment by eshepelyuk** [comment]
@Mogztter [yes](http://plantuml.com/ditaa)

**Comment by Mogztter** [comment]
Oh that's great, I can work on this feature if you want 😎

**Comment by eshepelyuk** [comment]
I'd be the gladest person if you will :)

**Comment by mojavelinux** [comment]
I'd be pretty darn glad too! :beers:

**Comment by mojavelinux** [comment]
I have an outdated prototype I had started if you need a reference.

See https://github.com/mojavelinux/asciidoctor-plantuml.js/commit/2207f4ac93176c60228e23ac7754a20e8438e90b

It probably needs some work, but I figured I'd share just in case.
