### ISSUE TITLE
Add support for included files (node.js)

### ISSUE THREAD

**Issue by metametadata** [eshepelyuk/asciidoctor-plantuml.js#29]
This is a feature request following an advice from
https://github.com/asciidoctor/asciidoctor-browser-extension/issues/79#issuecomment-403891225

In the end it'd cool to be able to render PlantUML diagrams in `Asciidoc Browser Extension` from external files, e.g.:

```
plantuml::xxxx.puml[format=png]
```

**Comment by eshepelyuk** [comment]
The most confusing for me is how to make this work in `Antora` ?

I suppose processing of `include` should be different depending on the env 

- browser
- nodejs
- antora

 @Mogztter maybe it's easier to fake the functionality in browser extension by reading content and injection it into a document before passing to `asciidoctor-plantuml` ?

**Comment by eshepelyuk** [comment]
test

**Comment by eshepelyuk** [comment]
qwe

**Comment by jvmlet** [comment]
I wonder, even if this feature is  implemented, how plantuml server will treat below snippet (with inner include) ?
 ````uml
@startuml
!include ./another.iuml // innner include
blah
blah
@enduml
````

**Comment by Mogztter** [comment]
> BTW [...] include::./haa-overview.iuml[haa-overview,png] doesn't work with antora

@jvmlet Could you please open a new issue?

> I wonder, even if this feature is implemented, how plantuml server will treat below snippet (with inner include) ?

I don't think it's possible to include a file when using the PlantUML server (ie. the file won't be resolved). I believe it can only work when using the CLI.

**Comment by mojavelinux** [comment]
I was thinking more about this. Why not use the AsciiDoc include directive instead of the PlantUML include directive? (as @Mogztter was suggesting). Then it will just work.

```
include::./haa-overview.iuml[haa-overview,png]
```

That's invalid syntax. It should be something like:

```
include::partial$haa-overview.iuml[]
```

The target has to come from the Antora content catalog, which means it needs to be in either the partials or examples directory.

**Comment by Mogztter** [comment]
> I was thinking more about this. Why not use the AsciiDoc include directive instead of the PlantUML include directive? (as @Mogztter was suggesting). Then it will just work.

Indeed, I didn't thought about it 😉 
@jvmlet Could you confirm that the following is working:

```
[plantuml]
----
include::partial$haa-overview.iuml[haa-overview,png]
----
```
(or `include::example$haa-overview.iuml` as mentioned by Dan)
```
@startuml
include::partial$another.iuml[]
blah
blah
@enduml
```

The only downside is that it will only work in Antora.
If you are using the PlantUML CLI on `haa-overview.iuml`, the Asciidoctor include directive won't be resolved.

**Comment by mojavelinux** [comment]
> The only downside is that it will only work in Antora.

True, though for now you can use either an attribute reference as the prefix or a preprocessor conditional to select the include based on the environment.

**Comment by jvmlet** [comment]
Just tried `include::partial$haa-overview.iuml[]` and got non-processed uml content inserted into html page as is. Am I missing  some additional asciidoctorjs settings to process uml files without plantuml extension being installed ?

**Comment by Mogztter** [comment]
@jvmlet Could you share your document or at least a snippet?

```
[plantuml]
....
include::partial$haa-overview.iuml[]
....
```

`haa-overview.iuml` is in your [partials](https://docs.antora.org/antora/2.0/page/#partial) directory ?

> Am I missing some additional asciidoctorjs settings to process uml files without plantuml extension being installed ?

What do you mean "without plantuml extension being installed"?

**Comment by jvmlet** [comment]
Here is my layout :
![image](https://user-images.githubusercontent.com/6664858/62450922-ed315280-b775-11e9-9c98-0fdef3fece5c.png)

Content of `globals.iuml` :
````
!define send(from,to, message) from->to : message
````


In `admin-server-interactions.adoc` :
````
[plantuml]
----
include::partial$admin-server-interactions.iuml[]
----
````
Gives me 
````
Error: No such file: http://www.plantuml.com/plantuml/png/bP1D2eCm44RtSufqfQBOA-Yow_O2qOnsC6PAVbeB7hu9HN0XXSugtuEyV9d6UMbzc3MSoFGwA1JrUTJSIUrgIXpWJf4EpBxZ9KRPUxRYXLshPZ803etAjrW9ZptFLxHFjA8iHPKzT1Z9948zrYFwctIJouk
i08i-M2Dy0h2kwszNbSc4TwOsBAH9slV53BmtKin7mkqKQw6YRvDuwz-dtS4dU88qJTJ4jNq0
````
 
Uml files without `!include`s are rendered as expected.

**Comment by Mogztter** [comment]
You need to replace `!include ./globals.iuml` by `include::partial$globals.iuml[]`

**Comment by jvmlet** [comment]
Same error

**Comment by jvmlet** [comment]
Anyway, these kind of solutions  don't allow me to develop uml files with `my favorite UML editor`.
I ended up with copying all uml files under `assets/images` directory and using `image:nameOfUmlFile.png` in adoc files. 
Before running Antora docker I run Plantuml docker from the root folder (docker-mounted) of all FS cloned  repositories ....

@mojavelinux ,I wish Antora be more sophisticated to support existing tools . Lack of extensions (comparing to AsciiDoctorJ), restriction to access something in FS that might be generated during build process (gradle for example) leaves a lot of space for improvements.

**Comment by Mogztter** [comment]
Could you please paste the stack with thr `include::` directive?

**Comment by mojavelinux** [comment]
@jvmlet This is not the appropriate forum to complain about Antora. And frankly, I find your remarks rather insensitive.

**Comment by jvmlet** [comment]
Sorry for misunderstanding @mojavelinux, but I didn't mean to complain about Antora. I find it a great addition to Asciidoctor ecosystem. Just provided a feedback  about Antora as a user to try to  help to  make it  better software. IMHO,  the Asciidoctor with it's growing community and integration capabilities is the best in class documentation tool. Sorry again, but English is not my mother tongue, that could lead for such misunderstanding.

**Comment by jvmlet** [comment]
@Mogztter, unfortunately I don't have the stacktrace anymore, but the exception was thrown during HTTP Get when  trying to download the generated image. No exception was thrown during  posting the uml to plantuml server which I believe failed because !include was not processed properly.

**Comment by Mogztter** [comment]
@jvmlet yes but the PlantUML server returns an image with the error message.
I believe that the error is not the same since `!include` is not in the source anymore (ie. replaced by the Asciidoctor include directive `include::`)

**Comment by jvmlet** [comment]
Will try to recreate the case tomorrow

**Comment by jvmlet** [comment]
All 3  files (`agent-server-interactions.adoc`,`agent-server-interactions.iuml`  and `globals.iuml`)  under `partials` directory.

`agent-server-interactions.adoc` :
````
[plantuml]
----
include::partial$agent-server-interactions.iuml[]
----
````

`agent-server-interactions.iuml` :
````
@startuml
include::partial$globals.iuml
send(tecomAgent, tecomServer ++ ,'managementService.getTasks()')
@enduml
````

`globals.iuml` :
````
!define send(from,to, message) from->to : message
````

Here is the full stacktrace :
````
Error: No such file: http://www.plantuml.com/plantuml/png/ZL0n3i8m3DppYWn8RKNL1tGg8sAWedmW95OKaJXHul1-qa855GkUx3lvxkmXaOYKdMK6fSqA-ZuKm0YxqzRVX4sTcLccey-14qZl9eWF8u4bG5Klo443KljX8VBzdhUL4oWqk4A-TpeDT1NfdkgcQbW4oX4
vpG0hOXkNqMPjyCVagrL-aWARFtA4HMlDS87W8nsnd6ujg35wbILj8frFhpnh3MKgRtW2
    at Object.httpGet [as get] (/usr/local/share/.config/yarn/global/node_modules/asciidoctor-plantuml/dist/node/node-http.js:31:11)
    at read (/usr/local/share/.config/yarn/global/node_modules/asciidoctor-plantuml/dist/node/node-fs.js:15:19)
    at Object.module.exports.save (/usr/local/share/.config/yarn/global/node_modules/asciidoctor-plantuml/dist/node/fetch.js:13:20)
    at createImageSrc (/usr/local/share/.config/yarn/global/node_modules/asciidoctor-plantuml/dist/node/asciidoctor-plantuml.js:37:37)
    at processPlantuml (/usr/local/share/.config/yarn/global/node_modules/asciidoctor-plantuml/dist/node/asciidoctor-plantuml.js:67:24)
    at self.process (/usr/local/share/.config/yarn/global/node_modules/asciidoctor-plantuml/dist/node/asciidoctor-plantuml.js:98:16)
    at Object.apply (/usr/local/share/.config/yarn/global/node_modules/asciidoctor.js/dist/node/asciidoctor.js:22093:21)
    at Object.Opal.yieldX (/usr/local/share/.config/yarn/global/node_modules/opal-runtime/src/opal.js:1464:18)
    at Proxy.$$call (/usr/local/share/.config/yarn/global/node_modules/opal-runtime/src/opal.js:18246:25)
    at Opal.send (/usr/local/share/.config/yarn/global/node_modules/opal-runtime/src/opal.js:1660:19)
````

**Comment by jvmlet** [comment]
I've changed the antora settings like this:

````
asciidoc:
  extensions:
    - asciidoctor-plantuml
  attributes:
    plantuml-server-url: 'http://localhost:8080'
#    plantuml-fetch-diagram: true
````

The  `plantuml-fetch-diagram` is **false**, and this is the rendered image :

![image](https://user-images.githubusercontent.com/6664858/62523355-3f3cab80-b83c-11e9-917c-0b5975cfcd05.png)

**Comment by Mogztter** [comment]
The include directive in `agent-server-interactions.iuml` is incorrect. You forgot to add `[]`:

```
@startuml
include::partial$globals.iuml[]

send(tecomAgent, tecomServer ++ ,'managementService.getTasks()')
@enduml``

**Comment by jvmlet** [comment]
Sorry, I DID use `include::partial$globals.iuml[]`,  see the generated image.

**Comment by Mogztter** [comment]
Could you try to add an empty line before the include directive? It appears that the include directive is not processed/ignored by Asciidoctor. I will try to reproduce this issue.

```
@startuml

include::partial$globals.iuml[]

send(tecomAgent, tecomServer ++ ,'managementService.getTasks()')
@enduml
```

**Comment by Mogztter** [comment]
The generated image and the source don't match, I don't see `group tecomService` in the source.

**Comment by jvmlet** [comment]
I've trimmed the iuml, here the  full listing :

````
@startuml

include::partial$globals.iuml[]

group tecomService
send(tecomAgent, tecomServer ++ ,'managementService.getTasks()')
return tasks
end

group tecomPlugin
send(tecomAgent,tecomAgent,doScan)
send(tecomAgent, tecomServer ++ ,'pluginService.ReportInstalledProducts()')
return OK
end
@enduml
````

The  empty  lines don't appear in the image somehow:
![image](https://user-images.githubusercontent.com/6664858/62527726-626b5900-b844-11e9-9135-fa644f8eea8b.png)

**Comment by akosma** [comment]
The problem is that `plantuml-encoder` (referenced by this plugin) does not support included files (using the PlantUML syntax). I'm trying to figure out a solution after forking said component.

**Comment by akosma** [comment]
I have just submitted [a pull request](https://github.com/markushedvall/plantuml-encoder/pull/11) with the required code to replace `!include ....` PlantUML statements with the corresponding contents.
