### ISSUE TITLE
Does asciidoctor.js support graphviz diagrams?

### ISSUE THREAD

**Issue by Skilly** [eshepelyuk/asciidoctor-plantuml.js#32]
I'm able to use asciidoctor.js in Chrome to successfully view asciidoctor documents containing plantuml diagrams, however Graphviz diagrams are not rendered. Are Graphviz diagrams currently supported, or are there plans to support them in asciidoctor.js?

(I'm running on Windows, have the Graphviz msi installed and have the GRAPHVIZ_DOT environment variable set.)

**Comment by eshepelyuk** [comment]
There's opened issue #16 addressing this.
