### ISSUE TITLE
Implement substitutions support inside plantuml block

### ISSUE THREAD

**Issue by JGrenier** [eshepelyuk/asciidoctor-plantuml.js#38]
The attributes substitution doesn't work .

here is an example : 

```
:bloc-annotation: testing annotation

[subs="attributes"]
[plantuml]
....
@startuml
 
rectangle "Bloc 1" <<$archimate/network>> as blk1 #lightblue 

rectangle "bloc 2" <<$archimate/network>> as blk2 #lightgray 

blk1 ==> blk2 : {bloc-annotation}

@enduml
....
```
in the resulting diagram {bloc-annotation} has not been replaced.

May be a missing preprocessor call ?

**Comment by eshepelyuk** [comment]
It's not implemented at all as far as I understand. @mojavelinux @Mogztter could you confirm that such functionality should be explicitely implemented in this extension ?

**Comment by mojavelinux** [comment]
The responsibility to honor the subs falls on the extension. This gives the extension the most flexibility of what to do with the lines of text.

**Comment by Mogztter** [comment]
And if I'm not mistaken, we should use `AbstractBlock#applySubstitutions` if we want to apply subs.

https://github.com/asciidoctor/asciidoctor.js/blob/07288833d54bcd99690f68945f30cdd6cf43e1b3/src/asciidoctor-core-api.js#L271-L273

**Comment by mojavelinux** [comment]
Yes, though that method requires computing the subs. There's a method on the node named resolve_subs that can do this (and take in all the incremental subs into effect).

However, we might end up introducing a method which is a bit more high level.
