### ISSUE TITLE
The extension should use readContents to fetch the remote images

### ISSUE THREAD

**Issue by Mogztter** [eshepelyuk/asciidoctor-plantuml.js#43]
The main advantage is that Asciidoctor.js is aware of the JavaScript environment and will use XMLHttpRequest in a browser environment.
Potentially it will make the "fetch diagram" feature available in a browser environment.
Though we will still need to provide a VFS or to embed the image in the HTML document.

`AbstractNode.read_contents` method: 

https://github.com/asciidoctor/asciidoctor/blob/dd5c0e38a011d97295c37075b7ec7331aa7e21cd/lib/asciidoctor/abstract_node.rb#L541

Currently it's not working in Node.js because the implementation is using the [`xmlhttprequest` module](https://www.npmjs.com/package/xmlhttprequest) and this module does not support binary data 😞

**Comment by Mogztter** [comment]
Should be fixed in: https://github.com/asciidoctor/asciidoctor.js/pull/634
I will add a test.

**Comment by Mogztter** [comment]
There's a few issues that need to be fixed in Opal in order to read binary data (with the Asciidoctor method `read_contents`):

https://github.com/opal/opal/pull/1920
https://github.com/opal/opal/pull/1919

**Comment by elia** [comment]
@Mogztter both the PRs are merged 👍 🚀

**Comment by Mogztter** [comment]
Yay thanks Elia 😃

**Comment by Mogztter** [comment]
According to Dan, `AbstractNode.read_contents` and `AbstractNode.read_asset` were designed to read text file (encoded in utf-8).
In our case we want to read remote images so I think we should use our own function.

**Comment by mojavelinux** [comment]
@Mogztter I'm happy to revisit those upstream methods, perhaps introduce a new one. I'm just establishing what the assumption is currently.
