### ISSUE TITLE
The extension should support data-uri

### ISSUE THREAD

**Issue by Mogztter** [eshepelyuk/asciidoctor-plantuml.js#44]
When `data-uri` is enabled the images will be embed in the HTML document:
https://asciidoctor.org/docs/asciidoc-syntax-quick-reference/#images

**Comment by djencks** [comment]
Documentation might be a good idea, but AFAICT there isn't anything to do here in this plugin.  Right now, specifying data-uri globally (to override Antora's feeble attempt to disable data-uri) and svg results in working data: uris when this plugin is used in Antora.  There's a problem with base64 encoding pngs in Antora with data-uri but it doesn't appear to have anything to do with this extension, as it occurs with direct links to pngs, both to the PlantUML server and static images.

**Comment by djencks** [comment]
The problem with data-uri with png is in asciidoctor 1.5.9.  In https://github.com/djencks/asciidoctor-plantuml.js/tree/issue-44-data-uri I've upgraded to @asciidoctor/core 2.0.3 and all the tests work fine, and data URIs extracted from the test look correct in html.  The tests in this branch might be worth adding after an asciidoctor upgrade although they don't really test any functionality of the extension.

**Comment by eshepelyuk** [comment]
Sorry, I don't follow the conversation. Does any work needed ? ANy input needed, Should we close this issue ?

**Comment by djencks** [comment]
After we close https://github.com/eshepelyuk/asciidoctor-plantuml.js/issues/76, I'd like to document the interaction of data-uri with this extension and write some tests, some of which will be disabled pending an asciidoctor.js upgrade.
