### ISSUE TITLE
The basename of the generated file should be reproductible

### ISSUE THREAD

**Issue by Mogztter** [eshepelyuk/asciidoctor-plantuml.js#45]
I think the basename of the generated file should be reproductible.
Maybe we could use the last part of the URL ? For instance the diagram generated from the URL: http://www.plantuml.com/plantuml/svg/SoWkIImgAStDuN8lpSp9IIpDJLNGjLDmBKjFpQlaSaZDIm7A0G00 will produce a file named `SoWkIImgAStDuN8lpSp9IIpDJLNGjLDmBKjFpQlaSaZDIm7A0G00.svg` ?

**Comment by eshepelyuk** [comment]
What about some sort of URL hash ?

**Comment by stephenc** [comment]
For what it's worth: https://github.com/eshepelyuk/asciidoctor-plantuml.js/pull/30 already had the feature that the file name would be based on the hash of the diagram content: https://github.com/eshepelyuk/asciidoctor-plantuml.js/pull/30/files#r238612166

**Comment by Mogztter** [comment]
@stephenc Thanks for the heads up.

I've created several issues based on your initial work to improve the integration with Antora.

It might be a good idea to use the `crypto` library to remove a dependency but we will still something in the browser. To be consistent we may still want to use the same library... But maybe Webpack can provide a shim for the browser ?

Apart from that the implementation is almost identical. I'm just using the encoded diagram content (+ server URL) instead of the content diagram.
