### ISSUE TITLE
Extension should consume lines from the block reader

### ISSUE THREAD

**Issue by mojavelinux** [eshepelyuk/asciidoctor-plantuml.js#52]
The extension is not consuming the lines from the block reader. Instead, it's working on a copy. As a result, the lines still get parsed as non-literal content after the extension code runs (even though those parsed lines never make their way to the AST).

This problem can be observed by processing a document with the following block:

```
[plantuml]
....
@startuml

[Component1] -down-> [Component2]
[Component2] -down-> [Component3]

@enduml
....
```

After the extension processes the block, the core processor goes on to process the following lines:

```
@startuml

[Component1] -down-> [Component2]
[Component2] -down-> [Component3]

@enduml
```

This leads to a warning. (The reason for the warning has to do with an obscure parsing issue in Asciidoctor, but nonetheless proves that Asciidoctor is still parsing these lines).

This is happening because the lines are read using `reader.getString()` instead of reader.read(). The `getString()` method only peeks at the lines in the reader, it doesn't consume them.

For some reason, the `read()` method isn't mapped in this scenario, so it's necessary to call `reader.$read()` for the time being. Perhaps @Mogztter can shed some light on why that's the case.

**Comment by mojavelinux** [comment]
@Mogztter In the Asciidoctor.js API, we need to make it clear that `getString()` returns the remaining lines on the reader as a string without consuming those lines. We should also make it clear that `read()` consumes the remaining lines and returns the result as a string.

(The reason for both styles is because sometimes you want to see what is there without consuming. But ultimately, a block should consume all the lines on the block reader).

**Comment by mojavelinux** [comment]
Here's a minimal example of that obscure parsing bug.

```
[a] b [c]
paragraph
```

Nonetheless, the core processor should never even be seeing these lines.

**Comment by Mogztter** [comment]
> For some reason, the `read()` method isn't mapped in this scenario, so it's necessary to call `reader.$read()` for the time being. Perhaps @Mogztter can shed some light on why that's the case.

It's mapped on `master` (unreleased):

https://github.com/asciidoctor/asciidoctor.js/blob/d0e226ae4030a083e4e641d77bb875ec0c999a95/src/asciidoctor-core-api.js#L1871-L1873

> @Mogztter In the Asciidoctor.js API, we need to make it clear that `getString()` returns the remaining lines on the reader as a string without consuming those lines. We should also make it clear that `read()` consumes the remaining lines and returns the result as a string.

Indeed we should clarify the documentation. I think we should state that:
* `get*` methods return a copy and do not consume the lines
* `read*` methods consume the lines

https://github.com/asciidoctor/asciidoctor.js/issues/675

**Comment by mojavelinux** [comment]
Exactly. Thanks for the insight!

**Comment by eshepelyuk** [comment]
@mojavelinux @Mogztter I'm interested in implementing this, but not sure if it's possible to create a test for the feature.
May you suggest ?

**Comment by mojavelinux** [comment]
I'd simply use the example in the description. If that renders without warning, then it works. You can check the logger to see if a warning was issued.

**Comment by eshepelyuk** [comment]
@mojavelinux I'd be appreciated for an example of how to check Asciidoctor logger, but if you don't have any - I'll try to figure it out myself.

**Comment by mojavelinux** [comment]
@Mogztter has written a whole chapter on it here https://asciidoctor-docs.netlify.com/asciidoctor.js/processor/logging-api/
