### ISSUE TITLE
Add support for included files (browser)

### ISSUE THREAD

**Issue by eshepelyuk** [eshepelyuk/asciidoctor-plantuml.js#53]
Followup to #29

**Comment by akosma** [comment]
I have just submitted [a pull request at `plantuml-encoder`](https://github.com/markushedvall/plantuml-encoder/pull/11) with the required code to replace `!include ....` PlantUML statements with the corresponding contents. If the author merges this in the library, this issue should be solved. WIl let you know as soon as I hear from the developer.

**Comment by anb0s** [comment]
I'm facing the [issue](https://github.com/asciidoctor/asciidoctor-vscode/issues/233) in the [asciidoctor-vscode](https://github.com/asciidoctor/asciidoctor-vscode) plugin that also uses **asciidoctor-plantuml.js**. I'm using the setting with local PlantUML server:
```
asciidoc.preview.attributes": {
    //"plantuml-server-url": "http://plantuml.com/plantuml"
    "plantuml-server-url": "http://localhost:8080"
},
```
and want to use files with `!include` . 

**How can i help to verify the PR from @akosma to make it available?**

Thanks!

**Comment by anb0s** [comment]
Still no answer from plantuml-encoder maintainer :(

**Comment by eshepelyuk** [comment]
Maybe it worth forking encoder and implement feature in forked version ?

**Comment by anb0s** [comment]
The feature is implemented by @akosma in the fork:
https://github.com/akosma/plantuml-encoder/commits/master

@eshepelyuk : is it possible to use from master branch or is a released version needed?

**Comment by eshepelyuk** [comment]
@anb0s i didn't understand your question.
Is the forked version available in npm ? If yes, you could provide a PR for this issue, replacing current module with that forked one.

**Comment by anb0s** [comment]
@eshepelyuk i'm new to node.js, but now understand how packaing etc. is working.
I've created new scoped package with the fixes from @akosma and pusblished: @anb0s/plantuml-encoder@1.5.1

**Comment by anb0s** [comment]
see PR #80
