### ISSUE TITLE
Can use plantuml in included adocs

### ISSUE THREAD

**Issue by hauer-io** [eshepelyuk/asciidoctor-plantuml.js#56]
You can not use plantuml in included files, because antora fails with error: 
"Duplicate image: 1.0@antora_puml:ROOT:079bd6453a30089d164645a5c69ac134ff5062a9.png"

See the issue in the example [https://github.com/hauer-io/asciidoctor-plantuml-antora](example)

**Comment by hauer-io** [comment]
But you can use it in partials.

**Comment by anoff** [comment]
I stumbled across the same issue; have you found any use case where you want to render it both as an included and standalone page @hauer-io ?

**Comment by hauer-io** [comment]
We include it in multiple *adoc-Files and this works just fine.
