### ISSUE TITLE
External uml file not found

### ISSUE THREAD

**Issue by jvmlet** [eshepelyuk/asciidoctor-plantuml.js#58]
Running below snippet 
````
[plantuml]
----
include::./haa-overview.iuml[haa-overview,png]
----
````
doesn't work with antora, getting
````
asciidoctor: ERROR: introduction.adoc: line 19: include target not found: ./haa-overview.iuml
````

**Comment by djencks** [comment]
You need to use antora coordinates to your included file, and I believe it needs to be in the partials or examples family unless you give it an .adoc extension.  I'm pretty sure you also need to put the target and format in with [plantuml] rather than as part of the include instruction.
