### ISSUE TITLE
Adding images multiple times is not avoided when using Antora

### ISSUE THREAD

**Issue by andreas-schilling** [eshepelyuk/asciidoctor-plantuml.js#59]
Currently it is not avoided that the same PlantUML rendering is added multiple times, resulting in the Antora content catalog to throw an error `duplicate file`.
This happens e.g. in the following situation: you have a page (e.g. `chapter1.adoc`) that is used individually (e.g. referenced from the main navigation) but also included as a partial somewhere else (e.g. within an `index.adoc` to provide the full documentation as one large document). If `chapter1` uses a PlantUML rendering that is cached to a file, it is tried to add it a second time to the content catalog (https://github.com/eshepelyuk/asciidoctor-plantuml.js/blob/master/src/asciidoctor-plantuml.js#L145)

Prior to adding the file it should be checked whether it already exists in the content catalog, e.g. using its function `#getById()`.

I can also provide a PR for this.

**Comment by eshepelyuk** [comment]
Hi @andreas-schilling PR is welcomed. unfortunately don't have enough time for the project maintenance :(

**Comment by andreas-schilling** [comment]
PR on the way.
