### ISSUE TITLE
Use a "standard" structure for the project

### ISSUE THREAD

**Issue by Mogztter** [eshepelyuk/asciidoctor-plantuml.js#6]
I think we should use a "standard" structure for the project. It will make it easier to configure tools in the JavaScript ecosystem.

Something like:

```sh
asciidoctor-plantuml.js
  |- package.json
  |- /dist
  |- /src
    |- index.js
  |- /spec
    |- asciidoctor-plantuml.spec.js
  |- /examples
    |- convert-fetch.js
    |- convert.js
    |- plantuml.adoc
```

**Comment by eshepelyuk** [comment]
Is there any _reliable guide_ for `standard` project structure in JS ? 
I saw many project using `lib` as src directory and `index.js` as an entry point and this is a little weird

**Comment by Mogztter** [comment]
> Is there any reliable guide for standard project structure in JS ?

I'm not sure but there are a few conventions:

* `/dist` - contains compiled and minified versions of the library (contains generated files, so this directory should not be versioned)
* `/examples` - contains examples :wink: 
* `lib` or `src` - contains the source code (i tend to prefer `src`)
* `/test` or `spec` - contains tests

> I saw many project using lib as src directory and index.js as an entry point and this is a little weird

Indeed you can also use an `index.js` at the root of the project and require modules/libraries contained in the `lib` folder.

Both approaches are valid.

**Comment by Mogztter** [comment]
> is this a blocker for #5 ?

Not really we could make it work anyway but I think it's will be easier to configure and to understand if we have this "common" structure in place.

> What about jasmine helper ? put to spec as well ?

We could or we could also consider that this file is a configuration file and let it at the root of the project. There's not right answer here.
The important part is to have a dedicated directory for:
* the source code
* the generated code (compiled, minified...)
* the tests
* the examples (if any)

**Comment by eshepelyuk** [comment]
1. plz proceed with option from original post
1. keep current name of entrypoint (i.e. do not use `index.js`)
1. put jasmine helper into `spec` folder
