### ISSUE TITLE
Change request: support for ditaa SVG generation

### ISSUE THREAD

**Issue by niborb** [eshepelyuk/asciidoctor-plantuml.js#70]
hi,

As mentioned in the readme, only PNG generation is supported.
> Only PNG generation is supported for Ditaa diagrams.

I was wondering whether SVG support is something that is planned to be implemented? Or are there specific reasons SVG is not being supported.

**Comment by eshepelyuk** [comment]
Hello

This restriction has nothing to do with this plugin. Instead It's a limitation of `PlantUML Server` that is used as backend for the plugin

Plz refer to the last line of `Ditaa` section http://plantuml.com/ditaa
