### ISSUE TITLE
$apply_subs only takes two arguments

### ISSUE THREAD

**Issue by Mogztter** [eshepelyuk/asciidoctor-plantuml.js#71]
We should remove the last argument from this line:

https://github.com/eshepelyuk/asciidoctor-plantuml.js/blob/b808c2da6e4be7bf6c77b062e088a319d75de00d/src/asciidoctor-plantuml.js#L49

`apply_subs` only takes two arguments: https://github.com/asciidoctor/asciidoctor/blame/v2.0.10/lib/asciidoctor/substitutors.rb#L75

**Comment by eshepelyuk** [comment]
Hi @Mogztter 
Why doesn't any test fail ? Is there a possibility to add some test for that ?

**Comment by Mogztter** [comment]
As far as I know, in JavaScript, the number of arguments is not checked (even in strict mode).

So `parent.$apply_subs(diagramText, parent.$resolve_subs(subs), true)` is effectively the same as `parent.$apply_subs(diagramText, parent.$resolve_subs(subs), true)` (ie. the last parameter will be ignored).
The code definition is wrong but it will work at runtime. I've noticed this error because I was running the same code in JRuby.

Not sure what the last parameter means in this context. Do you remember?

**Comment by eshepelyuk** [comment]
Hi, have no idea :((
Will remove the code a later bit today.
Do you need a new release for this ?

**Comment by Mogztter** [comment]
No rush, the code is somehow working so it's not critical :wink:
