### ISSUE TITLE
Support for Kroki

### ISSUE THREAD

**Issue by akosma** [eshepelyuk/asciidoctor-plantuml.js#75]
[Kroki](https://kroki.io/) supports the same diagrams as PlantUML and more, and uses an almost identical interface as the PlantUML server: pass an encoded string in the URL, get an image back.

The difference is that Kroki supports a larger number of diagram types: BlockDiag (BlockDiag, SeqDiag, ActDiag, NwDiag), C4 (with PlantUML), Ditaa, Erd, GraphViz, Mermaid, Nomnoml, PlantUML, SvgBob and UMLet.

It would be fantastic to add support for Kroki in this project, would you be willing to accept a pull request in this direction?

**Comment by eshepelyuk** [comment]
@akosma could you raise this issues in ?
https://gitter.im/asciidoctor/asciidoctor

long story short, personally I don't think `kroki` support should be put into this extension, instead a dedicated one should be created, maybe sharing the same code or creating monorepo project.

But I'd like to hear the opinion of @mojavelinux and @Mogztter :))

And, of course, I will be extremely happy to receive a PR about such feature :)
Thanks in advance.

**Comment by akosma** [comment]
I've just posted the question there. Actually it makes totally sense to have a separate plugin, and it is true it would be great to "fork" this project and use it as a basis, as the basic interaction with Kroki would be extremely similar to this one. Thanks!

**Comment by Mogztter** [comment]
@akosma I've already wrote an extension for Kroki: https://github.com/mogztter/asciidoctor-kroki (heavily inspired by this extension)
