### ISSUE TITLE
Release 1.5.0: Mismatch of git source and npm distribution

### ISSUE THREAD

**Issue by rocec** [eshepelyuk/asciidoctor-plantuml.js#79]
The contents of the module installed by `npm i asciidoctor-plantuml@1.5.0` do not match the source code of [Release 1.5.0](https://github.com/eshepelyuk/asciidoctor-plantuml.js/releases/tag/1.5.0).

This was found during a discussion on https://gitter.im/antora/users, investigating why inline and interactive SVG do not work as documented with the (presumed) 1.5.0 version installed by npm.

**Comment by eshepelyuk** [comment]
Hi, @rocec could you provide a link to a chat or a screen with details ?

**Comment by rocec** [comment]
Sure, sorry for being too brief.

Here is my message in the gitter chat starting the following discussion: https://gitter.im/antora/users?at=5e2ffe91d9895b17c3a202f0.

Then, to reproduce it easily:
* Use `npm i asciidoctor-plantuml@1.5.0` to install locally.
* Inspect `node_modules/asciidoctor-plantuml/dist/node/asciidoctor-plantuml.js`:
  * It is clearly different from [asciidoctor-plantuml.js](https://github.com/eshepelyuk/asciidoctor-plantuml.js/blob/ddebf7b19416b524940d7561d92ba5a449b1b296/src/asciidoctor-plantuml.js) as it is associated with the release on GitHub.
  * In particular, and that is how I stumbled over it, the entire handling of inline and interactive SVGs is missing.

**Comment by eshepelyuk** [comment]
Thanks, i will try to check it out during weekends.

**Comment by stephenc** [comment]
@rocec inline and interactive images don't work even if you use the latest source (at least for me) I had to change the implementation to get them to work... filing an issue with the details

**Comment by stephenc** [comment]
@rocec cf https://github.com/eshepelyuk/asciidoctor-plantuml.js/issues/81
