### ISSUE TITLE
Inline and interactive images doesn't actually work

### ISSUE THREAD

**Issue by stephenc** [eshepelyuk/asciidoctor-plantuml.js#81]
When running with antora, the links do not work. Looking at the asciidoctor source code it seems that the root cause is the options are being passed in a way that doesn't align with the expectations of the HTML5 renderer.

Specifically: https://github.com/asciidoctor/asciidoctor.js/blob/41b4fe065d055d882f6807b4d987ce93a9f89834/packages/core/src/asciidoctor-extensions-api.js#L558 takes three parameters, the 3rd parameter being the `opts`

That gets passed here: https://github.com/asciidoctor/asciidoctor/blob/cd9a7bcf7576c36da5eac2d63571369dbf13ae82/lib/asciidoctor/extensions.rb#L191

And the renderer only considers the `opts` https://github.com/asciidoctor/asciidoctor/blob/cd9a7bcf7576c36da5eac2d63571369dbf13ae82/lib/asciidoctor/converter/html5.rb#L629

Thus in https://github.com/eshepelyuk/asciidoctor-plantuml.js/blob/ddebf7b19416b524940d7561d92ba5a449b1b296/src/asciidoctor-plantuml.js#L86-L90 the additional entries in the `attrs` are ignored.

Likely fix is something like 

```
      const opts = {}
      if (inline) {
        opts['inline'] = ''
      } else if (interactive) {
        opts['interactive'] = ''
      }
      if (blockId) blockAttrs.id = blockId
      return processor.createImageBlock(parent, blockAttrs, opts)
```

I have verified that with similar to the above changes, i.e. https://github.com/stephenc/asciidoctor-plantuml.js/commit/e151da547e883feeacd27e6bc442a60f8b759f31#diff-443b5f4be235fc2d66073107add2b8cd that interactive images are correctly rendered with `<object>` tags

**Comment by stephenc** [comment]
@mojavelinux while we still have functionality that isn’t working yet, should the parameter be called `opts` rather than `options`?

Or which is `[plantuml%interactive]` equivalent to? `[plantuml,opts=interactive]` or `[plantuml,options=interactive]` or `[plantuml,opts=interactive,options=interactive]`?

**Comment by mojavelinux** [comment]
opts is an alias for options. Between the two, opts is preferred. Though even better is the shorthand `%interactive`. All those variations are handled internally by the core parser.

**Comment by stephenc** [comment]
Ok @mojavelinux so IIUC this plugin is looking for the `options` attribute is ok, this bug is that it doesn’t pass those options on to the html5 generator correctly as in my initial report of this issue

**Comment by mojavelinux** [comment]
The name of the variable doesn't matter. The options is a positional argument in the API and must be a Hash (i.e., Map).

**Comment by mojavelinux** [comment]
Oh, I see what you're saying. Yeah, the way options are being handled is not correct. Let me have a closer look.

**Comment by mojavelinux** [comment]
I remember now. The options have already been processed when they come into the process handler of the extension. So the extension should only be looking for attributes with the name `<optname>-option`. For example `inline-option`. There's no need for the extension to handle the conversion from `opts=inline` or `options=inline` to `inline-option`.

Here's how the code should look:

```js
const inline = 'inline-option' in attrs ||
  doc.getAttribute('plantuml-default-options') === 'inline'
const interactive = !inline &&
  ('interactive-option' in attrs['options'] ||
  doc.getAttribute('plantuml-default-options') === 'interactive')
```

Though this check seems rather lazy to me:

```js
doc.getAttribute('plantuml-default-options') === 'inline'
```

The global options should be split on a comma into an array and then consulted for the presence of the option name.

```
const defaultOpts = (doc.getAttribute('plantuml-default-options') || '').split(',')

...

defaultOpts.includes('inline')
```

Though even that doesn't follow the pattern in AsciiDoc. We would expect global options to be defined as:

```
:plantuml-inline-option:
```

or

```
:plantuml-options: inline
```

The term "default" is never used anywhere else in AsciiDoc.

Hope that helps.
