### ISSUE TITLE
Publish the dist directory on release

### ISSUE THREAD

**Issue by Mogztter** [eshepelyuk/asciidoctor-plantuml.js#9]
We should only publish the `dist` directory when doing a release.
I think Travis should perform the release and publish the package to the npmjs registry (this is what we are doing in Asciidoctor.js).

Related to #5 and #8

**Comment by eshepelyuk** [comment]
@Mogztter would you be so kind to help on this ?
Currently the release process is completely manual. I'm just calling 

     $ npm publish

Is any automation required to publish just `dist` folder ? Are you going to provide scripts that will populate that fodler with proper files ?

**Comment by Mogztter** [comment]
> would you be so kind to help on this ?

@eshepelyuk Sure I will 😃 
The idea is to trigger a release when a tag is pushed. Travis will do the build, run the tests, generate the `dist` directory and then publish the release on the npmjs registry (using `npm publish`).

**Comment by eshepelyuk** [comment]
Ok, it means that I can trigger release from GitHub directly (via creating GitHub release, that its creating a tag), right ?

**Comment by Mogztter** [comment]
\o/
